# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0eec342254577bf21c1cca4920911b02b78309df8e9916298ae7216dccfa19bb19eceba346ea152e84298ce89d88c96952f561bdf100900b955be9e08dc20686

test:
  secret_key_base: 0adeae0b86374a82a14350f8ad9cb0ec5052a105e9e4a2598b775c8bdd965a8807ffc0e1d3135e9313a9be20dc1aa3810408c5c71eee975086c6567a1a0d4101

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
